import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import IndexView from '../src/views/IndexView';
import FormView from '../src/views/FormView';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <IndexView />
      <FormView />
    </div>
  );
}
